name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        shell: pwsh
        run: |
          Set-Location -Path "Build"
          .\build.ps1 1.2.3 4.5.6-rc1


#      - name: Install dependencies
#        run: dotnet restore MQTTnet.sln
#      - name: Build
#        run: dotnet build --configuration Release --no-restore MQTTnet.sln
#      - name: Test MQTTnet
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.Core.Tests\MQTTnet.Tests.csproj
#      - name: Test AspNetCore
#        run: dotnet test --no-restore --verbosity normal Tests\MQTTnet.AspNetCore.Tests\MQTTnet.AspNetCore.Tests.csproj